name: Validate JSONs

on: [pull_request, push]

jobs:
  verify-json-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Validate tags JSON
        uses: nhalstead/validate-json-action@0.1.3
        with:
          schema: ./examples/validate/schemas/tags_schema.json
          jsons: ./examples/json_example/json/tags.json,examples/basic_policy/iron_skillet/tags.json #path to tags file

      - name: Validate address objects JSON
        uses: nhalstead/validate-json-action@0.1.3
        with:
          schema: ./examples/validate/schemas/addr_obj_schema.json
          jsons: ./examples/json_example/json/addr_obj.json #path to address objects file

      - name: Validate address group JSON
        uses: nhalstead/validate-json-action@0.1.3
        with:
          schema: ./examples/validate/schemas/addr_group_schema.json
          jsons: ./examples/json_example/json/addr_group.json #path to address groups file

      - name: Validate nat JSON
        uses: nhalstead/validate-json-action@0.1.3
        with:
          schema: ./examples/validate/schemas/NAT_schema.json
          jsons: ./examples/json_example/json/nat.json #path to NAT policy file

      - name: Validate security policy JSON
        uses: nhalstead/validate-json-action@0.1.3
        with:
          schema: ./examples/validate/schemas/sec_policy_schema.json
          jsons: ./examples/json_example/json/sec_policy.json,examples/basic_policy/iron_skillet/sec_policy.json  #path to security policy file

      - name: Validate services JSON
        uses: nhalstead/validate-json-action@0.1.3
        with:
          schema: ./examples/validate/schemas/services_schema.json
          jsons: ./examples/json_example/json/services.json #path to services file

      - name: Validate anti spyware JSON
        uses: nhalstead/validate-json-action@0.1.3
        with:
          schema: ./examples/validate/schemas/anti_spyware_schema.json
          jsons: ./examples/json_example/json/spyware.json,./examples/basic_policy/iron_skillet/spyware.json # change this to the anti-spyware JSON path

      - name: Validate antivirus JSON
        uses: nhalstead/validate-json-action@0.1.3
        with:
          schema: ./examples/validate/schemas/antivirus_schema.json
          jsons: ./examples/json_example/json/antivirus.json,./examples/basic_policy/iron_skillet/antivirus.json # change this to the antivirus JSON path

      - name: Validate file blocking JSON
        uses: nhalstead/validate-json-action@0.1.3
        with:
          schema: ./examples/validate/schemas/file_blocking_schema.json
          jsons: ./examples/json_example/json/file_blocking.json,./examples/basic_policy/iron_skillet/file_blocking.json # change this to the file-blocking JSON path

      - name: Validate vulnerability JSON
        uses: nhalstead/validate-json-action@0.1.3
        with:
          schema: ./examples/validate/schemas/vulnerability_schema.json
          jsons: ./examples/json_example/json/vulnerability.json,./examples/basic_policy/iron_skillet/vulnerability.json # # change this to the vulnerability JSON path

      - name: Validate wildfire analysis JSON
        uses: nhalstead/validate-json-action@0.1.3
        with:
          schema: ./examples/validate/schemas/wildfire_schema.json
          jsons: ./examples/json_example/json/wildfire.json,./examples/basic_policy/iron_skillet/wildfire.json # change this to the wildfire JSON path